# -*- coding: utf-8 -*-
"""Fandi3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-zSQKolhNpXVZuPF8_aqdKcHd38CID8
"""

!pip install tiktoken

"""**Select Text**"""

english_text = """The Great Barrier Reef is headed for a "grim future" and will suffer a "rapid coral decline" by 2050 but parts may recover if global warming is kept below 2C, a new study has found.

Researchers at the University of Queensland (UQ) used modelling to simulate the lifecycles of certain coral species and found that some were better at adapting to warmer oceans and could help new coral grow.

Reefs near cooler-water currents were also more resilient, giving a "glimmer of hope" to the natural wonder, which has suffered severe climate-induced heat stress in recent years.

The study warned that curbing carbon emissions was crucial to allow coral to recover and avoid a "near collapse" of the reef.

Dr Yves-Marie Bozec, who led the research, said the modelling of more than 3,800 individual reefs that make up the Great Barrier Reef looked at their "eco-evolutionary dynamics". This included how corals interact with each other, how they deal with warmer water and corals in naturally cooler areas.

"We ran all of those factors with the most up-to-date climate projections - and the news was not good," he said.

"We forecast a rapid coral decline before the middle of this century regardless of the emissions scenario."

The Great Barrier Reef is one of the world's most biodiverse ecosystems, stretching more than 2,300km (1,400 miles) off Australia's north-east coast.

It has suffered four significant marine heatwaves between 2016 and 2022, causing much of its coral to expel the algae which gives them life and colour - a process called bleaching, which is often fatal.

A recent report found that parts of the Great Barrier Reef had suffered the largest annual decline in coral cover since records began nearly 40 years ago."""

"""**Reason for choosing:**  
I chose this passage because it is an informative piece of scientific reporting written in natural, formal English. It contains both technical vocabulary and general expressions, making it ideal for cross-linguistic tokenization analysis.

**Chinese Translation**
"""

chinese_text = """一项新研究发现，大堡礁正走向一个“黯淡的未来”，到2050年将经历“珊瑚的快速衰退”，但如果全球变暖被控制在2摄氏度以下，部分地区仍有可能恢复。

昆士兰大学的研究人员使用建模方法模拟了某些珊瑚物种的生命周期，发现其中一些更能适应变暖的海洋环境，并可能帮助新的珊瑚生长。

靠近冷水洋流的珊瑚礁也表现出更强的韧性，为这片自然奇观带来了一线“希望”。近年来，大堡礁因气候变化导致的高温压力而遭受严重影响。

研究警告称，遏制碳排放对于珊瑚恢复和避免大堡礁“几近崩溃”至关重要。

领导研究的伊夫-玛丽·博泽克博士表示，他们对构成大堡礁的3800多个独立珊瑚礁进行了“生态-进化动态”建模，包括珊瑚之间的相互作用、应对暖水的方式以及处于自然冷水区的珊瑚表现。

“我们将所有这些因素与最新的气候预测结合起来——结果并不乐观，”他说。

“无论排放情景如何，我们预测本世纪中叶前珊瑚将迅速衰退。”

大堡礁是世界上生物多样性最高的生态系统之一，全长超过2300公里，位于澳大利亚东北海岸外。

2016年至2022年间，大堡礁经历了四次显著的海洋热浪，导致大量珊瑚排出赋予它们生命和颜色的藻类——这一过程被称为“白化”，通常是致命的。

最近的一份报告发现，大堡礁部分区域的珊瑚覆盖率出现了自近40年前有记录以来最大的年度下降。"""

"""**Polish Translation**"""

polish_text = """Wielka Rafa Koralowa zmierza ku „ponurej przyszłości” i do 2050 roku doświadczy „szybkiego spadku koralowców”, ale niektóre części mogą się odbudować, jeśli globalne ocieplenie zostanie utrzymane poniżej 2°C – wynika z nowego badania.

Naukowcy z Uniwersytetu Queensland (UQ) wykorzystali modelowanie do symulacji cykli życiowych niektórych gatunków koralowców i odkryli, że niektóre z nich lepiej przystosowują się do cieplejszych oceanów i mogą wspierać wzrost nowych koralowców.

Rafy położone w pobliżu chłodniejszych prądów morskich były również bardziej odporne, dając „promyk nadziei” temu cudowi natury, który w ostatnich latach ucierpiał z powodu stresu cieplnego wywołanego zmianami klimatu.

Badanie ostrzega, że ograniczenie emisji dwutlenku węgla jest kluczowe, aby umożliwić odbudowę koralowców i uniknąć „niemal całkowitego załamania” rafy.

Dr Yves-Marie Bozec, który kierował badaniami, powiedział, że modelowanie ponad 3800 indywidualnych raf tworzących Wielką Rafę Koralową analizowało ich „dynamikę eko-ewolucyjną”. Obejmowało to interakcje między koralowcami, ich reakcję na cieplejsze wody oraz zachowanie w chłodniejszych obszarach.

„Uwzględniliśmy wszystkie te czynniki w najnowszych prognozach klimatycznych – i wyniki nie były dobre” – powiedział.

„Prognozujemy szybki spadek liczby koralowców przed połową tego stulecia, niezależnie od scenariusza emisji.”

Wielka Rafa Koralowa jest jednym z najbardziej bioróżnorodnych ekosystemów na świecie, rozciągającym się na ponad 2300 km u północno-wschodniego wybrzeża Australii.

Między 2016 a 2022 rokiem doświadczyła czterech znaczących fal upałów morskich, które spowodowały, że wiele koralowców wydaliło glony nadające im kolor i życie – proces zwany bieleniem, często śmiertelny.

Niedawny raport wykazał, że części Wielkiej Rafy Koralowej odnotowały największy roczny spadek pokrywy koralowej od prawie 40 lat."""

"""**Tokenization**"""

import tiktoken

enc = tiktoken.get_encoding("cl100k_base")

def tokenize_text(text):
    tokens = enc.encode(text)
    token_strs = [enc.decode([t]) for t in tokens]
    return tokens, token_strs

eng_tokens, eng_strs = tokenize_text(english_text)
chi_tokens, chi_strs = tokenize_text(chinese_text)
pol_tokens, pol_strs = tokenize_text(polish_text)

print(f"English: {len(eng_tokens)} tokens")
print(f"Chinese: {len(chi_tokens)} tokens")
print(f"Polish: {len(pol_tokens)} tokens")

"""**Word-level statistics**"""

import re
import pandas as pd

def word_token_stats(text, token_strs, lang="English"):
    if lang == "Chinese":
        words = list(text.replace(" ", "").replace("\n", ""))
    else:
        words = re.findall(r'\S+', text)
    token_counts = [len(enc.encode(w)) for w in words]
    total_words = len(words)
    total_tokens = len(token_strs)
    one = sum(1 for c in token_counts if c == 1) / total_words
    two = sum(1 for c in token_counts if c == 2) / total_words
    three_plus = sum(1 for c in token_counts if c >= 3) / total_words
    avg = total_tokens / total_words
    return {
        "total_words": total_words,
        "total_tokens": total_tokens,
        "%1_token": round(one * 100, 2),
        "%2_tokens": round(two * 100, 2),
        "%3+_tokens": round(three_plus * 100, 2),
        "avg_tokens_per_word": round(avg, 2)
    }

stats = pd.DataFrame([
    word_token_stats(english_text, eng_strs, "English"),
    word_token_stats(chinese_text, chi_strs, "Chinese"),
    word_token_stats(polish_text, pol_strs, "Polish")
], index=["English", "Chinese", "Polish"])

stats

"""**Example words per language**"""

examples = {
    "English": ["barrier", "coral", "evolutionary", "research", "temperature"],
    "Chinese": ["大堡礁", "气候变化", "温室气体", "研究", "白化"],
    "Polish": ["koralowców", "bioróżnorodnych", "prognozujemy", "czynnikiem", "cieplarnianych"]
}

for lang, words in examples.items():
    print(f"\n--- {lang} ---")
    for w in words:
        t = enc.encode(w)
        print(f"{w} → {t} ({len(t)} tokens)")

"""**Visualization (Bar chart)**"""

import matplotlib.pyplot as plt

plt.bar(stats.index, stats["avg_tokens_per_word"], color=["skyblue", "salmon", "lightgreen"])
plt.title("Average Tokens per Word by Language")
plt.ylabel("Average Tokens per Word")
plt.xlabel("Language")
plt.show()

"""### Observations
- **English** had the lowest token-per-word ratio (~1.1), because spaces clearly separate words and most are short.
- **Polish** had slightly higher tokens per word (~1.3), due to inflectional endings and long compound words.
- **Chinese** was the most expensive (~1.8 tokens per “word”) because there are no spaces and each character is often one token.
- This shows that tokenization cost depends on language structure: alphabets, morphology, and spacing all affect token counts.

"""