# -*- coding: utf-8 -*-
"""Fandi4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8GP8SgVY3IQDAg41IREEGTc0hWKVOol
"""

texts = [
    "This food delivery app is super convenient and the orders arrive really fast.",
    "The interface looks outdated and the app freezes quite often.",
    "It works okay overall, nothing amazing but nothing terrible either.",
    "After the latest update there are many bugs and it crashes a lot.",
    "Customer support replied quickly and solved my problem right away.",
    "There are way too many ads, every time I open the app a popup appears.",
    "The overall experience is great, I will definitely keep using it.",
    "The map location is inaccurate and my order was sent to the wrong address several times.",
    "The design is clean and modern, I really like how it looks.",
    "Sometimes the app just gets stuck and I have to force close it.",
    "The prices are acceptable and there are plenty of discounts.",
    "Notifications are too frequent and it feels really annoying.",
    "The installation was easy and it was quick to get started.",
    "The QR scanner fails to recognize codes most of the time, which is very frustrating.",
    "After the redesign the interface looks much better than before.",
    "Some features are hidden too deep in the menus and hard to find.",
    "There are many promotions, but the rules are a bit confusing.",
    "The app is quite stable and I rarely see it crash.",
    "It asks for too many permissions, which makes me uncomfortable.",
    "Overall it is fine, nothing particularly impressive but it works."
]

import pandas as pd

df = pd.DataFrame({"text": texts})
df.to_csv("data.csv", index=False)
df.head()

!pip install --quiet openai pandas tqdm matplotlib

import os
import json

import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
from IPython.display import display

from openai import OpenAI


api_key = os.getenv("OPENROUTER_API_KEY")
if api_key is None:
    raise ValueError("Please set the OPENROUTER_API_KEY environment variable before running this notebook.")


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
)

system_prompt = """
You are a sentiment classification assistant for English app reviews.
Given one user review about a mobile app, your task is to decide the overall sentiment label.

Rules:
1. You must choose exactly one label from the following:
   - positive
   - neutral
   - negative
2. If the review is clearly positive or recommending the app, choose "positive".
3. If the review is clearly negative or complaining, choose "negative".
4. If the review is mild, mixed, or neither positive nor negative, choose "neutral".

Output format:
You must output exactly one JSON object:
{"label": "<one of: positive, neutral, negative>"}
Do NOT output anything else.
"""

def classify_text(text: str) -> str:
    try:
        response = client.chat.completions.create(
            model="minimax/minimax-01",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            max_tokens=20
        )

        content = response.choices[0].message.content
        data = json.loads(content)
        label = data.get("label", "").lower().strip()

        if label in allowed_labels:
            return label
        return "error"

    except Exception as e:
        print("Error:", e)
        return "error"

tqdm.pandas(desc="Classifying")

df["label"] = df["text"].progress_apply(classify_text)

display(df)

df.to_csv("labeled.csv", index=False, encoding="utf-8")
print("Saved labeled.csv")

print("Label counts:")
label_counts = df["label"].value_counts()
print(label_counts)

error_count = (df["label"] == "error").sum()
print("Errors:", error_count)

label_counts.plot(kind="bar")
plt.title("Label Distribution")
plt.show()

"""**Mini Analysis**

The model produced clear and consistent results across the 20 app reviews, and a strong pattern emerged: positive and negative sentiments were much easier for the model to classify, while neutral cases were more ambiguous. Reviews that contained mixed opinions or balanced statements tended to fall into the neutral category, but sometimes leaned slightly positive or negative depending on wording. No error outputs occurred after limiting the response to a small number of max tokens, which suggests that earlier errors were caused by overly large default settings rather than classification difficulty.

One class that was somewhat harder to separate was the neutral label, especially in reviews that expressed mild praise or mild dissatisfaction without strong sentiment. To improve reliability in the future, I could provide a few labeled examples (few-shot prompting) or simplify the input text by removing irrelevant details. Another option would be adding clearer rules in the system prompt to distinguish neutral tone from weakly positive or weakly negative tone. The label distribution chart shows a roughly balanced mix of positive and negative reviews, with fewer neutral reviews overall, which reflects the nature of the dataset.
"""